services:
  - type: web
    name: soil-fertility-status-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Changed from test.app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free